repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-json
        files: "(integrations/.*/manifest\\.json|sample-context/.*\\.json|schemas/.*\\.json)"
      - id: check-symlinks
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
