name: Upload artifacts and trigger deployment

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    name: Build and test
    uses: ./.github/workflows/build_and_test.yml

  upload-to-s3:
    name: Upload to S3
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: github.repository == 'launchdarkly/integration-framework-private'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Assume AWS role
        uses: launchdarkly/common-actions/aws-auth@1a4ed44fb65ee340cfe86234b79fc1bf606bfe25
        with:
          role-session-name: 'UploadToS3'
          iam-role-arn: 'arn:aws:iam::554582317989:role/github-actions-integration-framework-private'
      - name: Upload artifacts to S3
        run: ./scripts/upload_artifacts_to_s3.sh

  trigger-deployment:
    name: Trigger deployment
    runs-on: ubuntu-latest
    needs: [build-and-test, upload-to-s3]
    if: github.repository == 'launchdarkly/integration-framework-private'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Send webhook
        run: ./scripts/send_webhook.sh
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          THUMB_SEEKER_TOKEN: ${{ secrets.THUMB_SEEKER_TOKEN }}
